### 请求 /infra/file-config/create 接口 => 成功
GET {{appBusinessUrl}}/uctp/car-info/page
Content-Type: application/json
tenant-id: {{adminTenentId}}
Authorization: Bearer {{token}}

{
    "pageNo": 1,
    "pageSize": 10,
    "vin": null,
    "brand": null,
    "salesStatus": null,
    "checkStatus": null
}


