###查询商户虚拟账户资产详情
GET {{appBusinessUrl}}/uctp/account/get
Content-Type: application/json
tenant-id: {{adminTenentId}}

###保证金释放
POST {{appBusinessUrl}}/uctp/account/cash/release
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "contractNo": "2312321"
}

###保证金回填-利润
POST {{appBusinessUrl}}/uctp/account/cash/profit/back
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "accountNo": "1234567",
  "tranAmount": 1000,
  "contractNo": "3213213"
}

###保证金回填
POST {{appBusinessUrl}}/uctp/account/cash/back
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "accountNo": "1234567",
  "tranAmount": 100,
  "contractNo": "332211"
}

###待回填保证金
POST {{appBusinessUrl}}/uctp/account/cash/difference
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "accountNo": "1234567"
}

###保证金实占
POST {{appBusinessUrl}}/uctp/account/cash/deduction
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "contractNo": "332211"
}

###保证金预占
POST {{appBusinessUrl}}/uctp/account/cash/reserve
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "accountNo": "1234567",
  "tranAmount": 11100,
  "contractNo": "2312321"
}

###保证金提取-提取成功后返回我的保证金页面模型数据
POST {{appBusinessUrl}}/uctp/account/cash/withdraw
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "accountNo": "1234567",
  "tranAmount": 1100,
  "revision": 42
}

###保证金交易明细查询
POST {{appBusinessUrl}}/uctp/account/cash/list
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "accountNo": "1234567",
  "type": 3,
  "pageNo": 1,
  "pageSize": 27
}

###保证金充值-充值成功后返回我的保证金页面模型数据
POST {{appBusinessUrl}}/uctp/account/cash/recharge
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "accountNo": "1234567",
  "tranAmount": 11111111111111,
  "revision": 41
}

###保证金详情-我的保证金
GET {{appBusinessUrl}}/uctp/account/cash/detail?accountNo=1234567
Content-Type: application/json
tenant-id: {{adminTenentId}}

###商户银行信息查询
GET {{appBusinessUrl}}/uctp/account/cash/bankInfo?accountNo=666
Content-Type: application/json
tenant-id: {{adminTenentId}}

